export default {
  data: [{
        "id": 195,
        "commercialNum": "CM02021121603",
        "commercialName": "非线上非收款码二",
        "commercialPhone": "",
        "orgId": 57,
        "orgName": null,
        "twoBranch": 4,
        "branchName": null,
        "riskType": "004",
        "warningList": [{
          "id": 375,
          "value": "1",
          "label": "商户地址异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 1,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }, {
          "id": 376,
          "value": "2",
          "label": "pos机异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 2,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }],
        "warnings": null
      }, {
        "id": 196,
        "commercialNum": "CM02021121604",
        "commercialName": "非线上收款码pos",
        "commercialPhone": "",
        "orgId": 57,
        "orgName": null,
        "twoBranch": 4,
        "branchName": null,
        "riskType": "004",
        "warningList": [{
          "id": 375,
          "value": "1",
          "label": "商户地址异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 1,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }, {
          "id": 376,
          "value": "2",
          "label": "pos机异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 2,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }, {
          "id": 378,
          "value": "4",
          "label": "营业执照异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 4,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }],
        "warnings": null
      }, {
        "id": 197,
        "commercialNum": "CM02021121607",
        "commercialName": "线上非收款码pos",
        "commercialPhone": "",
        "orgId": 57,
        "orgName": null,
        "twoBranch": 6,
        "branchName": null,
        "riskType": "004",
        "warningList": [{
          "id": 376,
          "value": "2",
          "label": "pos机异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 2,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }, {
          "id": 378,
          "value": "4",
          "label": "营业执照异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 4,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }],
        "warnings": null
      }, {
        "id": 198,
        "commercialNum": "CM02021121612",
        "commercialName": "线上收款码二",
        "commercialPhone": "",
        "orgId": 57,
        "orgName": null,
        "twoBranch": 11,
        "branchName": null,
        "riskType": "004",
        "warningList": [{
          "id": 375,
          "value": "1",
          "label": "商户地址异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 1,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }, {
          "id": 376,
          "value": "2",
          "label": "pos机异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 2,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }],
        "warnings": null
      }, {
        "id": 199,
        "commercialNum": "CM0123456789000",
        "commercialName": "VansMall",
        "commercialPhone": "15678904590",
        "orgId": 59,
        "orgName": null,
        "twoBranch": 2,
        "branchName": null,
        "riskType": "003",
        "warningList": [{
          "id": 375,
          "value": "1",
          "label": "商户地址异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 1,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }, {
          "id": 376,
          "value": "2",
          "label": "pos机异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 2,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }, {
          "id": 378,
          "value": "4",
          "label": "营业执照异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 4,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }],
        "warnings": null
      }, {
        "id": 200,
        "commercialNum": "CM0123451234500",
        "commercialName": "线上小店",
        "commercialPhone": "15555308000",
        "orgId": 57,
        "orgName": null,
        "twoBranch": 2,
        "branchName": null,
        "riskType": "004",
        "warningList": [{
          "id": 375,
          "value": "1",
          "label": "商户地址异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 1,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }, {
          "id": 376,
          "value": "2",
          "label": "pos机异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 2,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }, {
          "id": 378,
          "value": "4",
          "label": "营业执照异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 4,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }],
        "warnings": null
      }, {
        "id": 201,
        "commercialNum": "CM0202112248888",
        "commercialName": "新装商户机构",
        "commercialPhone": "",
        "orgId": 57,
        "orgName": null,
        "twoBranch": 2,
        "branchName": null,
        "riskType": "004",
        "warningList": [{
          "id": 376,
          "value": "2",
          "label": "pos机异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 2,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }],
        "warnings": null
      }, {
        "id": 202,
        "commercialNum": "CM019900000000",
        "commercialName": "非线上商户001",
        "commercialPhone": "",
        "orgId": 57,
        "orgName": null,
        "twoBranch": 2,
        "branchName": null,
        "riskType": "004",
        "warningList": [{
          "id": 377,
          "value": "3",
          "label": "法人身份证异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 3,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }, {
          "id": 378,
          "value": "4",
          "label": "营业执照异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 4,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }],
        "warnings": null
      }, {
        "id": 203,
        "commercialNum": "CM0123450000000",
        "commercialName": "实体无收款码",
        "commercialPhone": "14444400000",
        "orgId": 57,
        "orgName": null,
        "twoBranch": 2,
        "branchName": null,
        "riskType": "003",
        "warningList": [{
          "id": 376,
          "value": "2",
          "label": "pos机异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 2,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }, {
          "id": 378,
          "value": "4",
          "label": "营业执照异常",
          "type": "commercialWarningType",
          "description": "商户异常类型",
          "sort": 4,
          "createTime": "2022-01-18 01:38:14",
          "updateTime": "2022-01-18 01:38:14",
          "remarks": "商户异常类型",
          "delFlag": "0"
        }],
        "warnings": null
  }]
}